filepath: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/01_raw/tcga_mutations_controlled.csv

uni_column: "Patient_ID"

text_column: "Alt_Sequence"

batch_size: 5

num_patients: 200 # default None, used to limit the data

chunk_size: 1  # the num of sequences to be concatenated

encoder_name: nt #dnabert2 # "hyenadna"  # or "DNABERT2"

tokenizer_type: ntKmer #dnabert2_bpe # "character_tokenizer"  # choose a suitable tokenizer based on model

device: "cuda"  # cuda, or "cpu" if you don't have a GPU

pooling_type: cls_token #max_pooling #mean_pooling #full_embedding, otherwise full_embedding

stack_feature: True  # Stack features for each patient

batch_size: 64

output_dir: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/04_feature
