filepath: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/01_raw/tcga_mutations_controlled.csv

uni_column: "Patient_ID"

text_column: "Alt_Sequence"

batch_size: 5

num_patients: 200 # default None, used to limit the data

chunk_size: 500  # the num of sequences to be concatenated

encoder_name: "dnabert2" # "hyenadna"  # or "DNABERT2"

tokenizer_type: "dnabert2_bpe" # "character_tokenizer"  # choose a suitable tokenizer based on model

device: "cuda"  # cuda, or "cpu" if you don't have a GPU

cls_token: False

stack_feature: True  # Set to true to stack features for each patient

batch_size: 64

output_dir: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/04_feature
