filepath: /mnt/bulk-uranus/lizhang/LiWorkSpace/genomics/data/01_raw/tcga_mutations_controlled.csv

pat_column: "Patient_ID"

mut_column: "Alt_Sequence"

num_patients: 1 # default None, specific number is used to limit the data

encoder_name: gv #nt #hd #db2

device: "cuda:0"  # or "cpu" if you don't have a GPU

pooling_type: mean_pooling

batch_size: 64

num_workers: 4

output_dir: /mnt/bulk-uranus/lizhang/LiWorkSpace/genomics/data/04_feature
