filepath: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/01_raw/tcga_mutations_controlled.csv

uni_column: "Patient_ID"

text_column: "Alt_Sequence"

num_patients: #2 # default None, used to limit the data

chunk_size: 1  # the num of sequences to be concatenated

encoder_name: dnabert2 #nt #hyenadna #ef

tokenizer_type: dnabert2_bpe #ntKmer #character_tokenizer #efOnehot  # choose a suitable tokenizer based on model

device: "cuda"  # cuda, or "cpu" if you don't have a GPU

pooling_type: mean_pooling #, otherwise cls_token/end_token

per_mut: True

stack_feature: True  # Stack features for each patient

batch_size: 64

output_dir: /mnt/bulk-io/lizhang/LiWorkSpace/genomics/data/04_feature
