raw_data:
  filepath: "./data/01_raw/tcga_mutations_controlled.csv"

columns:
  - Patient_ID
  - Alt_Sequence

text_column: "Alt_Sequence"

sequence_chunk_size: 500  # 用户自定义的抽取数目

encoder_name: "hyenadna"  # or "DNABERT2"

tokenizer_type: "character_tokenizer"  # choose a suitable tokenizer based on model

device: "cuda"  # cuda, or "cpu" if you don't have a GPU

output_dir: "./data/04_feature"
